### ISSUE TITLE
Cannot select newly created edges

### ISSUE THREAD

**Issue by samuelvkwong** [rwth-acis/syncmeta#159]
If you connect two elements by an edge, you cannot select the edge properly. If you refresh the page it will work again.

**Example**
When working with the bot model: When creating an incoming message that is supposed to follow another incoming message, a leadsTo connection element is needed. After creating the new incoming message element and connecting the previous incoming message to the new one, the label for the leadsTo connection must be set with the intent keyword. Clicking the leadsTo connection does not open up the window to edit the label like other connection elements. 

**Temporary fix**
Refresh the page. Though, sometimes it stops working after a bit.

**Comment by lakhoune** [comment]
The following error is logged by jsplumb when connecting the nodes
```
Exception has occurred: TypeError: Cannot read properties of null (reading '0')
  at EndpointDragHandler._drop (http://localhost:8000/build/build/widgets/widget.container.js:5121:60)
    at EndpointDragHandler.onStop (http://localhost:8000/build/build/widgets/widget.container.js:4922:46)
    at Object.<anonymous> (http://localhost:8000/build/build/widgets/widget.container.js:2949:36)
    at Object.stop (http://localhost:8000/build/build/widgets/widget.container.js:623:33)
    at Drag._dispatch (http://localhost:8000/build/build/widgets/widget.container.js:2492:61)
    at Drag.stop (http://localhost:8000/build/build/widgets/widget.container.js:2469:26)
    at Drag._upListener (http://localhost:8000/build/build/widgets/widget.container.js:2208:26)
```

**Comment by lakhoune** [comment]
After some debugging, I am now pretty sure that it is due to the fact that we delete the edge which is automatically created and forming it again in the same event listener:
https://github.com/rwth-acis/syncmeta/blob/f0fd1b9a1df8bbf966f73fb3d60cf296a7801068/build/widgets/widget.container.js#L53786-L53791
So jsplumb will check the connection after this callback was done and then throw an error because that original connection does not exist anymore
