### ISSUE TITLE
Copy:lib fails [yjs13]

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/syncmeta#66]
When building the project with Grunt ^1.5.0 the build fails due to a processing excpetion. The following error is logged. This behaviour is happening on the branch yjs13
```sh
grunt build --stack
Running "build" task

Running "clean:0" (clean) task
>> 8 paths cleaned.

Running "requirejs:compile" (requirejs) task

Running "copy:lib" (copy) task
Warning: An error occurred while processing a template (Unexpected token '*'). Use --force to continue.
SyntaxError: An error occurred while processing a template (Unexpected token '*').
    at Function (<anonymous>)
    at C:\Repositories\syncmeta\widgets\node_modules\lodash\lodash.js:14942:16
    at apply (C:\Repositories\syncmeta\widgets\node_modules\lodash\lodash.js:487:27)
    at C:\Repositories\syncmeta\widgets\node_modules\lodash\lodash.js:15326:16
    at apply (C:\Repositories\syncmeta\widgets\node_modules\lodash\lodash.js:489:27)
    at C:\Repositories\syncmeta\widgets\node_modules\lodash\lodash.js:6627:16
    at Function.template (C:\Repositories\syncmeta\widgets\node_modules\lodash\lodash.js:14941:20)
    at Object.template.process (C:\Repositories\syncmeta\widgets\node_modules\grunt\lib\grunt\template.js:70:27)
    at Object.processContent [as process] (C:\Repositories\syncmeta\widgets\Gruntfile.js:32:35)
    at Object.file._copy (C:\Repositories\syncmeta\widgets\node_modules\grunt\lib\grunt\file.js:328:26)

Aborted due to warnings.
```
so far I could not deduce which template might be causing the issue. 

Looking at StackOverflow [[1]](https://stackoverflow.com/questions/55461005/lodash-js-syntaxerror-unexpected-token) did not help much.

**Comment by BobCAE** [comment]
the template which failed to pass was the vendor font awsome file

**Comment by lakhoune** [comment]
the template which failed to pass was the vendor font awsome file
